### ISSUE TITLE
Create a tutorial video presenting what do the extensions do

### ISSUE THREAD

**Issue by tjw0lf** [sustmi/gnome-shell-extensions-sustmi#40]
What do you mean

historymanager-prefix-search plugin, the second command should be:

$ cp -RT gnome-shell-extensions-sustmi/historymanager-prefix-search ~/.local/share/gnome-shell/extensions/historymanager-prefix-search@sustmidown.centrum.cz

What does that do

historymanager-prefix-search plugin, I don't understand what this is for

**Comment by sustmi** [comment]
I am sorry, I thought that the issue was resolved as you already managed to install the extension.
The purpose of historymanager-prefix-search is described on the wiki: https://github.com/sustmi/gnome-shell-extensions-sustmi/wiki/HistoryManager-Prefix-Search .
The description is also in the README file.

Can you help me to make the purpose of the extension more clear?

**Comment by tjw0lf** [comment]
I still don't get it sorry. It seems you are being more clear then ever i din't mean to be disrespectful. If i have i apologize.

If you can do a tut with screen shots to help me understand or even a quick video on youtube would help?

**Comment by sustmi** [comment]
Ok, I will try create some kind of tutorial soon.

**Comment by sustmi** [comment]
Finally, here is a demo of HistoryManager Prefix Search extension: https://youtu.be/nSUpKyyM2-U .

**Comment by sustmi** [comment]
I am closing the issue. Feel free to open the topic again if you find the demo video insufficient.
