### ISSUE TITLE
Icons are misplaced when I drag a window to a workspace

### ISSUE THREAD

**Issue by glaubersm** [sustmi/gnome-shell-extensions-sustmi#48]
Hi
I use your extension on Arch with Gnome 3.26, my screencast shows the bug.

https://www.youtube.com/watch?v=jozCtM3VyPM

**Comment by sustmi** [comment]
Hi @glaubersm .
The issue was fixed in https://github.com/sustmi/gnome-shell-extension-windowoverlay-icons/commit/4c884dcbb03134bd1957ddf7f363eae64904b94a. The fix will be present in the next release.

*Note that https://github.com/sustmi/gnome-shell-extensions-sustmi repository is deprecated because I split the repository into two separate repositories so please post any new issues or pull requests to https://github.com/sustmi/gnome-shell-extension-windowoverlay-icons.*

**Comment by glaubersm** [comment]
I updated your extension today on Arch. The problem is still happening.

**Comment by sustmi** [comment]
What do you mean by "updated" - do you use exactly the commit https://github.com/sustmi/gnome-shell-extension-windowoverlay-icons/commit/4c884dcbb03134bd1957ddf7f363eae64904b94a?
I just want to make sure you use the fixed code before I dive into another long debugging session.

**Comment by glaubersm** [comment]
Today an update for your extension was available in gnome extensions website.
I don't know if this update includes your commit.

**Comment by sustmi** [comment]
Hi @glaubersm . Can you update the extension to v28 or higher and confirm that the issue does not occur any more?

**Comment by glaubersm** [comment]
My extension was installed from gnome shell extensions website and the problem is not happening anymore.

**Comment by sustmi** [comment]
Thanks for info @glaubersm . Closing the issue.
